# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ask_child_count.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChildCountUi:

    def ok_pressed(self):
        child_count = self.spinBox.value()
        self.Dialog.parent().child_count_label.setText(f"Кол-во детей: {child_count}")
        self.Dialog.parent().db_worker.save_child_count(child_count)
        self.Dialog.parent().child_count_is_known = True
        self.Dialog.parent().child_count = child_count
        self.Dialog.close()

    def cancel_pressed(self):
        self.Dialog.parent().child_count_label.setText(f'Кол-во детей: #Неизвестно!')
        self.Dialog.close()

    def __init__(self, dialog:QtWidgets.QDialog):
        self.Dialog = dialog
        self.verticalLayoutWidget = QtWidgets.QWidget(dialog)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.info_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ok_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ok_button.clicked.connect(self.ok_pressed)
        self.cancel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_button.clicked.connect(self.cancel_pressed)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(270, 115)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 2, 250, 110))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.info_text.setFont(font)
        self.info_text.setObjectName("info_text")
        self.verticalLayout.addWidget(self.info_text)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.info_text.setText(_translate("Dialog", "Введите кол-во пришедших сегодня\nдетей:"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
